name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
    linting-and-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                fetch-depth: 0
            
            - name: Setup Helm
              uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
            
            - name: Lint Helm Charts
              run: helm lint .
            
            - name: Install Kind Cluster
              uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
            
            - name: Test Helm Charts
              run: |
                for chart in ./; do
                    helm install test-release "$chart" --dry-run
                done
    success:
        needs:
            - linting-and-testing
        if: >- # run if at least one needed job has failed or all needed jobs have not been cancelled or skipped
            always() && (
                contains(join(needs.*.result, ','), 'failure')
                || (
                !contains(join(needs.*.result, ','), 'cancelled') 
                && !contains(join(needs.*.result, ','), 'skipped')
                )
            )
        runs-on: ubuntu-24.04
        steps:
        - name: Verify no failures occurred in needed jobs
            # if there are failures, false is executed and the job fails.
            run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
    
    deploy:
        needs:
            - success
        uses: ./.github/workflows/release.yml
        if: github.ref_name == github.event.repository.default_branch
        secrets: inherit
    