name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
    linting-and-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                fetch-depth: 0
            
            - name: Setup Helm
              uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
            
            - name: Lint Helm Charts
              run: helm lint .
            
            - name: Install Kind Cluster
              uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
            
            - name: Test Helm Charts
              run: |
                for chart in ./; do
                    helm install test-release "$chart" --dry-run
                done
            