name: Semantic Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HELM_REGISTRY_USERNAME: ${{ secrets.USERNAME }}
          HELM_REGISTRY_PASSWORD: ${{ secrets.TOKEN }}
        run: |
          npm install
          npx semantic-release