name: Semantic Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npm install
          npx semantic-release
      
      - name: Create charts folder
        run: |
          mkdir charts
          chmod 755 charts
      
      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      
      - name: Update Helm chart dependencies
        run: helm dependency update

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.2.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/position-pal
          username: ${{ secrets.USERNAME }}
          access-token: ${{ secrets.GHCR_TOKEN }}
          force: true
          chart-folder: "./"