name: Semantic Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
    
      - name: Find the version of Node from package.json
        id: node-version
        run: echo "version=$(jq -r .engines.node package.json)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npm install
          npx semantic-release
      
      - name: Push Helm chart to OCI compatible registry (Github)
        if: ${{ github.ref_type == 'tag' }}
        uses: bsord/helm-push@650e04843d399b727368d37022b576c6a6ff3291 # v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ secrets.USERNAME }}
          access-token: ${{ github.token }}
          force: true
          chart-folder: "./"
      
          